- .ko.yaml
- openshift/ci-operator/Dockerfile-git.in
- openshift/ci-operator/Dockerfile.in
- openshift/ci-operator/knative-images/bash/Dockerfile
- openshift/ci-operator/knative-images/controller/Dockerfile
- openshift/ci-operator/knative-images/creds-init/Dockerfile
- openshift/ci-operator/knative-images/entrypoint/Dockerfile
- openshift/ci-operator/knative-images/git-init/Dockerfile
- openshift/ci-operator/knative-images/gsutil/Dockerfile
- openshift/ci-operator/knative-images/kubeconfigwriter/Dockerfile
- openshift/ci-operator/knative-images/nop/Dockerfile
- openshift/ci-operator/knative-images/webhook/Dockerfile
- openshift/e2e-tests-openshift.sh
- tekton/ko/Dockerfile
After this PR the base image used will be UBI 8 for
- github.com/tektoncd/pipeline/cmd/nop,
- github.com/tektoncd/pipeline/cmd/kubeconfigwriter,
- github.com/tektoncd/pipeline/cmd/webhook,
- github.com/tektoncd/pipeline/cmd/controller
This PR is related to https://jira.coreos.com/browse/SRVKP-30
> First image port to UBI 8

- openshift/ci-operator/Dockerfile-git.in
- openshift/ci-operator/Dockerfile.in
- openshift/ci-operator/knative-images/bash/Dockerfile
- openshift/ci-operator/knative-images/controller/Dockerfile
- openshift/ci-operator/knative-images/creds-init/Dockerfile
- openshift/ci-operator/knative-images/entrypoint/Dockerfile
- openshift/ci-operator/knative-images/git-init/Dockerfile
- openshift/ci-operator/knative-images/gsutil/Dockerfile
- openshift/ci-operator/knative-images/kubeconfigwriter/Dockerfile
- openshift/ci-operator/knative-images/nop/Dockerfile
- openshift/ci-operator/knative-images/webhook/Dockerfile
Base image changed to UBI-8 for
- openshift/ci-operator/Dockerfile-git.in
- openshift/ci-operator/Dockerfile.in
- openshift/ci-operator/knative-images/bash/Dockerfile
- openshift/ci-operator/knative-images/controller/Dockerfile
- openshift/ci-operator/knative-images/creds-init/Dockerfile
- openshift/ci-operator/knative-images/entrypoint/Dockerfile
- openshift/ci-operator/knative-images/git-init/Dockerfile
- openshift/ci-operator/knative-images/gsutil/Dockerfile
- openshift/ci-operator/knative-images/kubeconfigwriter/Dockerfile
- openshift/ci-operator/knative-images/nop/Dockerfile
- openshift/ci-operator/knative-images/webhook/Dockerfile
> Resolves - https://jira.coreos.com/browse/SRVKP-30

- Makefile
We probably would not need to add the generate dockerfiles to the repo too, but
let's keep it as is for now
Ref: https://jira.coreos.com/browse/SRVKP-120?filter=-1
> generate-dockerfiles before doing a make install

- openshift/e2e-tests-openshift.sh
Upstream recently migrated its scripts from knative/test-infra to
tektoncd/plumbing, so we need this change to build master again 👼
Should fix https://github.com/openshift/tektoncd-pipeline/pull/30 automatic builds :angel: 
/cc @chmouel 
Signed-off-by: Vincent Demeester <vdemeest@redhat.com>
> Update e2e script to mirror upstream changes

- RELEASE_PROCESS.md
At present snippet to generate ci-operator/job and ci-operator/config files work only in zsh.
Changed it to use find command so that bash as well as zsh can be used also.
/cc @chmouel @vdemeester
> Make snippet compatible with bash also

- README.md
- RELEASE_PROCESS.md
- Add link to v0.5.2 release branch to Readme.
- Add instruction to generate release yaml to Release Readme.
- Remove outdate image generation instruction from Release Readme.
/cc @chmouel @sthaha @vdemeester
Signed-off-by: Khurram Baig kbaig@redhat.com
> Add v0.5.2 link to Readme and Update Release Readme

- RELEASE_PROCESS.md
- openshift/release/generate-release.sh
In order to eanble scraping for `/metrics` endpoint,a clusterwide
prometheus expects to have `openshift.io/cluster-monitoring`
lable on pipeline namespace.
This patch adds the `openshift.io/cluster-monitoring` lable
on pipeline namespace while generating `release.yaml`
fixes https://jira.coreos.com/browse/SRVKP-298
> Adds metrics configuration to pipeline

- openshift/e2e-tests-openshift.sh
Hack to get the TestSidecar working.
Full on discussion here (RH Only): https://coreos.slack.com/archives/CG5GV6CJD/p1568983413242300
We need to get https://github.com/tektoncd/pipeline/issues/1347 fixed to remove this hack.
```TODO```: rewrite e2e test and resolve_resource shell script in something else (python?), it becomes way too much spagethini-shelly and too much error prone 🍝
> Use upstream nop image to fix sidecar tests.

- Makefile
check-images didn't work properly and wasn't detecting if there is a new binary
that would need to be added,
Fixing it properly.
/cc @vdemeester @sthaha
> Fix check-images target

- openshift/e2e-tests-openshift.sh
Update `IGNORES` var in test script w.r.t upstream file renaming
Replaces
-readonly IGNORES="pipelinerun.yaml|private-taskrun.yaml|taskrun.yaml|gcs|taskrun-git-volume.yaml"
+readonly IGNORES="pipelinerun.yaml|pull-private-image.yaml|build-push-kaniko.yaml|gcs|git-volume.yaml"
Update e2e-tests-openshift.sh to ignore errors from `delete_test_resources_openshift`
as the following file renaming was done upstream:
```
examples/taskruns/taskrun.yaml → examples/taskruns/build-push-kaniko.yaml
examples/taskruns/taskrun-git-volume.yaml → examples/taskruns/git-volume.yaml
examples/taskruns/private-taskrun.yaml → examples/taskruns/pull-private-image.yaml
```
other changes in upstream in the patch that changed the file names
ref: https://github.com/tektoncd/pipeline/commit/3873c3ce5223f54cdd097215ebf7 …
> Fixes for CI Breakage due to upstream example modifications

- RELEASE_PROCESS.md
Fixes a minro typo in Release process documentation
Replaces
...Make sure you have all the files in there which is **two** in ci-operator/config and **one** in ci-operator/job... with
...Make sure you have all the files in there which is **one** in ci-operator/config and **two** in ci-operator/job...
> Improves Release Process Documentation

- openshift/resolve-yamls.sh
Add a sort to the `find $dir -name "*.yaml" | grep -vE $ignores | sort`
This patch will make sure that the yamls are resolved
in the order (numbered names) specified in config dir
`for yaml in $(find config -name "*.yaml" | grep -vE noignores); do`
```
config/webhook.yaml
config/config-observability.yaml
config/controller.yaml
config/300-task.yaml
...
```
`for yaml in $(find config -name "*.yaml" | grep -vE noignores | sort); do`
```
config/100-namespace.yaml
config/101-podsecuritypolicy.yaml
config/200-clusterrole.yaml
config/200-serviceaccount.yaml
config/201-clusterrolebinding.yaml
config/300-clustertask.yaml
...
```
> Improve resolve-yamls.sh

- Makefile
- openshift/ci-operator/knative-images/gcs-fetcher/Dockerfile
- openshift/resolve-yamls.sh
gcs-fetcher is no a binary from `./cmd`. It is an image which shoudl be built from a vendored
dependency `vendor/github.com/GoogleCloudPlatform/cloud-builders/gcs-fetcher/cmd/gcs-fetcher`
This patch adds the mechanism to build `vendor/github.com/GoogleCloudPlatform/cloud-builders/gcs-fetcher/cmd/gcs-fetcher`
in openshift-ci
(cherry picked from commit dde7d4ea75104216565479c3937fee0d93ed04e2)
> Add mechanism to build/tag gcs-fetcher image which is used by tekton-controller

- Makefile
- openshift/ci-operator/knative-images/gcs-fetcher/Dockerfile
- openshift/resolve-yamls.sh
gcs-fetcher is not a binary from `./cmd`. It is an image which shoudl be built from a vendored
dependency `vendor/github.com/GoogleCloudPlatform/cloud-builders/gcs-fetcher/cmd/gcs-fetcher`
This patch adds the mechanism to build `vendor/github.com/GoogleCloudPlatform/cloud-builders/gcs-fetcher/cmd/gcs-fetcher`
in openshift-ci
(cherry picked from commit dde7d4ea75104216565479c3937fee0d93ed04e2)
(cherry picked from commit 270f602ebe57fb6b3fe817721d09dfadf1d4fae7)
(cherry picked from commit bf885b9b65688953df2550849c46a026e4ee2798)
> Patch for build/tag gcs-fetcher image

- openshift/release/tektoncd-pipeline-v0.7.0.yaml
This pathc updates the v0.7.0 release.yaml with correct reference to `gcs-fetcher` image
> Add v0.7.0 release.yaml

- openshift/addons/pipeline-monitoring.yaml
- openshift/e2e-tests-openshift.sh
- openshift/release/generate-release.sh
- openshift/resolve-yamls.sh
In order to enable cluster-monitoring prometheus
to scrape the openshift pipeline metrics it requires
certain configuration such as "ServiceMonitor" and
list "pods, service etc" roles/rolebinding. This configuration can be
done through operator but it would create additional segway
and increase delta between upstream and downstream operator.
Instead, this patch alters `generate-release.sh` to append
above mentioned configuration in `release.yaml`.
Fixes https://jira.coreos.com/browse/SRVKP-298
> Adds OpenShift monitoring config

- Makefile
- openshift/release/update-to-head.sh
Add nightly tektoncd-pipeline yaml
On `update-to-head.sh` script which is run nightly, we add a nightly yaml file
generated with  :
```shell
./openshift/release/generate-release.sh nightly
```
If this gets validated properly this would get pushed to :
https://git.io/Jeu17
and people can just do a :
```shell
$ oc create -f https://git.io/Jeu17
```
to get the latest nightly
It references the images nightly generated pushed from CI with the quay mirroring :
https://git.io/Jeu1I
We added info in Makefile::check-images to make sure when there is a new image
to be added to the quay mirroring.
We fixed some error in `generate-release`
> Add nightly tektoncd-pipeline

- Makefile
- openshift/ci-operator/knative-images/bash/Dockerfile
- openshift/resolve-yamls.sh
* Add a check in check-images to make sure when upstream is  removing images we are not letting it lingering around
* Remove bash image
/cc @vdemeester @hrishin @sthaha @nikhil-thomas
> Remove bash and check removed images

- openshift/ci-operator/build-image/Dockerfile
This will bump the go version from 1.10
to 1.12 as the upstream has used feature
like strings.ReplaceAll() which got available
from 1.12
> Bump go version to 1.12

- openshift/e2e-tests-openshift.sh
Upstream has added flag to skip test
in which priviledged access is required and
can not be run on Openshift without that
Lets use the flag to skip that test in
our nightly and downstream CI
> Add flag to skip root access test

- openshift/resolve-yamls.sh
This patch removes extra spaces occuring in image tags
fixes
```
image:  <name>:<tag>
```
to
```
image: <name>:tag>
```
The reason for this change is the yaml lint errors in operator nightly builds
> Fix extra-space in resolved yaml manifest

- openshift/e2e-tests-openshift.sh
This fix has been tested in https://github.com/openshift/tektoncd-pipeline/pull/295/commits/97f79b30fbbef0b22b7c00e9eb557664a908cd0e
> Adds no-ci and cloud-event to ingore list

- Makefile
Now that master has the upstream "fix"
https://github.com/tektoncd/pipeline/commit/530f0843732f4db6de3597571710c501a923c320,
we can use this build tag to disable the GCP credentialprovider and
make OpenShift Pipeline work on GCP.
> Add disable_gcp build tag to make it run on GCP 🏃

- openshift/release/generate-release.sh
- Update label `pipeline.tekton.dev/release` to reflect actual version instead of `devel` on release.
> Reflect Tekton release version in Artifacts after release

- openshift/e2e-tests-openshift.sh
Modifies openshift/e2e-tests-openshift.sh with appropriate flags to skip RootUser Tests
Related to: https://github.com/tektoncd/pipeline/pull/2304
and https://github.com/openshift/tektoncd-pipeline/pull/364
changes in #2304 will not be available in upstream rc3, hence it is separately added in midstream rc3 branch through #364 
(cherry picked from commit d728e507307460d73d0386c6cb0d983d764c39a2)
> fix skip tests

- RELEASE_PROCESS.md
Add `make jobs` to the release process.
Eventhough our script snippets will generate both config and jobs, `sanitize-prow-jobs` is not
run. `make jobs` will do both generate jobs (which we are already doing) and `sanitize-prow-jobs`.
> Improve release doc

- openshift/ci-operator/uidwrapper
This will fix the passing argument to uidwrapper
Some arguments are not getting passed to
git-init
> Fix uidwrapper

- openshift/addons/pipeline-monitoring.yaml
The service name of tekton pipeline controller is http-metrics. The file has metrics. This patch fixes it.
> Fix ServiceMonitor endpoint

- openshift/e2e-tests-openshift.sh
Add a `while [[ ! -f ${waitFileName} ]];` based breakPoint mechanism (func)
to e2e-test script.
This will be useful when we want to make ci-debug prs and want control the test flow on ci.
This give better control and predictability compared to a `sleep <duration>` command.
**usage:**
create a breakpoint by adding
```
breakPoint <breakPointName>
```
to resume (run in pod `e2e`, container `test`)
```
touch <breakPointName>
```
note: breakPointName is a fileName. The breakPoint function waits until the file is created.
> Add a BreakPoint mechanism in test script

- openshift/resolve-yamls.sh
- Add Fix to Ill image replacement,  dynamically get the base image reference before running the tests
> Fix to pr-444 failure

- openshift/resolve-yamls.sh
since openshift takes care of th uid randomization and not allowing to set a fix
uuid under 1000620000
The error:
```40s         Warning   FailedCreate
replicaset/tekton-pipelines-webhook-55b98d698      Error creating: pods
"tekton-pipelines-webhook-55b98d698-" is forbidden: unable to validate against
any security context constraint:
[spec.containers[0].securityContext.securityContext.runAsUser: Invalid value:
1001: must be in the ranges: [1000620000, 1000629999]]```
> No need to set runasUser in openshift release.yaml

- openshift/e2e-tests-openshift.sh
Updated e2e script to run all yaml examples.
Earlier we use to do `oc apply -f tests-resolved.yaml` and some of the examples were not running because of `generateName` and it always use to give 
```
from server for: "tests-resolved.yaml": resource name may not be empty
```
and if we make it to
`oc create -f tests-resolved.yaml`  still fails with `already exist` because few examples are common between `v1alpha1` and `v1beta1` so in order to make it success
Created 2 namespaces
**tekton-pipeline-tests-yaml-alpha** --- For v1alpha1
**tekton-pipeline-tests-yaml-beta**   --- For v1beta1
Signed-off-by: Savita Ashture sashture@redhat.com
> Update e2e script to run all the yaml examples

- RELEASE_PROCESS.md
Add a note to mention the need and the steps to create a midstream
release tag, once the ci tests are green and the release artifacts are
merged
> Add note on tagging the midstream release

- openshift/release/release-notes.md
Add release notes from all the upstream releases after TP-1.1
These release notes are pulled from upstream releases v0.15.x and
v0.16.x
> Add TP-1.2 (v0.15.x, v0.16.x) release notes

- openshift/patches/0001-Remove-TestTaskRunRetry-too-much-flakyness.patch
- openshift/patches/0001-Skip-duplications-tests.patch
We update patches that are flaky on OpenShift.
Due of the move to latest client-go which add context everywhere, we have to
refresh the patches.
> Regenerate openshift patches

- openshift/e2e-tests-openshift.sh
This will set the SYSTEM_NAMESPACE env in
e2e script which will be further used
in e2e test
> Set SYSTEM_NAMESPACE env in e2e script

- openshift/ci-operator/build-image/Dockerfile
This commit changes the image `openshift/origin-release:golang-1.14`
(which is hosted on Docker Hub) to
`registry.svc.ci.openshift.org/openshift/release:golang-1.14` which is
a public repository as well. The main motivation being the CI failures
occurring due to Docker Hub's rate limiting.
> Move away from Docker Hub due to rate limiting

- Makefile
- openshift/ci-operator/build-image/Dockerfile
- openshift/resolve-yamls.sh
There is change in registry address and because of the [CI](https://github.com/openshift/tektoncd-pipeline/pull/635) failing
As part of this PR updating registry url.
/cc @piyush-garg @praveen4g0 @vdemeester
> Update registry URL from registry.svc.ci.openshift.org to registry.ci.openshift.org

- openshift/release/update-to-head.sh
Add a mechanism to preserve release.yaml from previous passed nightly build as a backup
> Modify update-to-head.sh
