openshift/tektoncd-pipeline

- Makefile
- OWNERS_ALIASES
fix install phase of Makefile so that all images can be built successfully
> fix Makefile

- openshift/ci-operator/Dockerfile-git.in
- openshift/ci-operator/Dockerfile.in
- openshift/ci-operator/generate-dockerfiles.sh
- openshift/ci-operator/knative-images/bash/Dockerfile
- openshift/ci-operator/knative-images/controller/Dockerfile
- openshift/ci-operator/knative-images/creds-init/Dockerfile
- openshift/ci-operator/knative-images/entrypoint/Dockerfile
- openshift/ci-operator/knative-images/git-init/Dockerfile
- openshift/ci-operator/knative-images/gsutil/Dockerfile
- openshift/ci-operator/knative-images/kubeconfigwriter/Dockerfile
- openshift/ci-operator/knative-images/nop/Dockerfile
- openshift/ci-operator/knative-images/webhook/Dockerfile
- openshift/e2e-tests-openshift.sh
- test/helm_task_test.go
- test/kaniko_task_test.go
- test/pipelinerun_test.go
- Update dockerfiles
- Add execution of e2e tests
> Update to use OCP 4

- openshift/release/README.md
- openshift/release/create-release-branch.sh
- openshift/release/update-to-head.sh
Same as openshift/knative-* repositories
Signed-off-by: Vincent Demeester <vdemeest@redhat.com>
> Add release scripts in master 👼

- OWNERS_ALIASES
and remove some old ones that was coming from knative-
> More approvers review

- README.md
/cc @arilivigni @sthaha @vdemeester
> Update README to 0.3.0

- README.md
/cc @arilivigni @sthaha @vdemeester
> Update README for 0.3.1 release

- README.md
- RELEASE_PROCESS.md
> Add Release Process

- openshift/ci-operator/Dockerfile-git.in
- openshift/ci-operator/Dockerfile.in
- openshift/ci-operator/knative-images/bash/Dockerfile
- openshift/ci-operator/knative-images/controller/Dockerfile
- openshift/ci-operator/knative-images/creds-init/Dockerfile
- openshift/ci-operator/knative-images/entrypoint/Dockerfile
- openshift/ci-operator/knative-images/git-init/Dockerfile
- openshift/ci-operator/knative-images/gsutil/Dockerfile
- openshift/ci-operator/knative-images/kubeconfigwriter/Dockerfile
- openshift/ci-operator/knative-images/nop/Dockerfile
- openshift/ci-operator/knative-images/webhook/Dockerfile
This updates ubi8 dev-preview base image to ubi8 generally
available base image
> Update base images to UBI8 GA

- Makefile
- openshift/ci-operator/knative-images/imagedigestexporter/Dockerfile
/cc @arilivigni @sthaha @vdemeester @hrishin
> Downstream release 0.4.0 CI setup

- RELEASE_PROCESS.md
/cc @arilivigni @sthaha @vdemeester @hrishin
> Update documentation with some nits and bits

- Makefile
Add makefile target instead of homegrown shell script
/cc @arilivigni @sthaha @vdemeester @hrishin
> Add makefile target to pull images from CI and push to quay

- README.md
- RELEASE_PROCESS.md
* Add openshift/0.4.0 to the list of release,
* Add makefile target information for pushing images
* Add info about how to generate release.yaml
* Some bad english fixes
/cc @vdemeester
> Update documentation for release

- openshift/e2e-tests-openshift.sh
Add a few other things to make it easier to run the script on a local
workstation for debugging the tests.
> Run E2E script with -e

- Makefile
- openshift/ci-operator/knative-images/pullrequest-init/Dockerfile
Will need to get this first merged : 
https://github.com/openshift/release/pull/4391
/cc @vdemeester
> Add pullrequest-init image

- Makefile
> Sync master with latest commit

- openshift/release/tektoncd-pipeline-v0.5.2.yaml
Release file for v0.5.2
/cc @chmouel @sthaha @vdemeester
Signed-off-by: Khurram Baig kbaig@redhat.com
> Release file for v0.5.2

- openshift/ci-operator/Dockerfile-git.in
- openshift/ci-operator/knative-images/creds-init/Dockerfile
- openshift/ci-operator/knative-images/git-init/Dockerfile
Those Dockerfile fails if ran on non RHEL8.
/cc @sthaha @chmouel @hrishin 
> Fix creds-init and git-init Dockerfile on openshift ci

- openshift/ci-operator/Dockerfile-git.in
- openshift/ci-operator/knative-images/creds-init/Dockerfile
- openshift/ci-operator/knative-images/git-init/Dockerfile
openssh-clients is called with a S
(it is without s only on debianies distros)
/cc @hrishin @vdemeester
>  Fix openssh client install

- RELEASE_PROCESS.md
Add a note to mention how/when the periodic (1hr) image mirroring is trriggered
> Improve Release documentation

- README.md
/cc @chmouel @nikhil-thomas @sthaha 
> Add link to release-0.7.0 👼

- openshift/release/tektoncd-pipeline-v0.7.0.yaml
- openshift/resolve-yamls.sh
Add release yaml manifest for openshift/tektoncd-pipeline v0.7.0
> Add v0.7.0 release.yaml

- openshift/release/tektoncd-pipeline-v0.8.0.yaml
cc: @sthaha @chmouel @vdemeester
> Adds tekton pipelines 0.8.0 release.yaml

- Makefile
- openshift/ci-operator/knative-images/gsutil/Dockerfile
- openshift/resolve-yamls.sh
/cc @vdemeester @hrishin @sthaha @nikhil-thomas
> Remove gsutils

- openshift/ci-operator/tekton-images/nop/Dockerfile
Can't find a more elegant way, but it works :p
> Fix the nop hack

- openshift/ci-operator/tekton-images/nop/Dockerfile
This may look easy but it is not,
tested properly as working see :
> Never understimate the power of a hack

- openshift/release/tektoncd-pipeline-v0.9.0.yaml
> Releasing release.yaml v0.9.0

- RELEASE_PROCESS.md
> Update RELEASE_PROCESS with latest

- openshift/resolve-yamls.sh
> Switch busybox images to UBI

- openshift/release/tektoncd-pipeline-v0.9.1.yaml
This add release.yaml v0.9.1 and make CI generate the images at the same time,
> Releasing release.yaml v0.9.1

- README.md
- RELEASE_PROCESS.md
> 0.9.2 and update a bit the release process to make it quicker

- openshift/release/tektoncd-pipeline-v0.9.2.yaml
> Releasing release.yaml v0.9.2

- openshift/ci-operator/tekton-images/gs-utils/Dockerfile
- openshift/resolve-yamls.sh
Add dockerfile for gs-util image
Also use this image in release-yaml
we are generating for downstream
release
> Add ubi based gs-util image

- openshift/release/tektoncd-pipeline-v0.9.2.yaml
- openshift/resolve-yamls.sh
This will fix the isue of extra space in controller
and webhook image name in release.yaml generated by script
Because of this yaml lint check is getting failed for
operator
> Remove extra space

- Makefile
> Make sure we compile the binary statically

- Makefile
Fix the order of flag provided to disable_gcp
Signed-off-by: Khurram Baig
> Fix Command to disable_gcp

- openshift/release/tektoncd-pipeline-v0.10.1.yaml
> Releasing release.yaml v0.10.1

- openshift/ci-operator/tekton-images/nop/Dockerfile
Same commit is tested on https://github.com/openshift/tektoncd-pipeline/pull/325
> Syncs nop image as per new ci

- openshift/resolve-yamls.sh
since we don't have an image and we use `google/cloud-sdk` for this.
> Remove gsutil from release.yaml

- OWNERS_ALIASES
Feel free to directly ping me if a review is desired. But, this should improve the bot auto-assigned reviewers and approvers.
> Removing myself from approver/reviewer roles

- openshift/e2e-tests-openshift.sh
- test/init_test.go
- test/kaniko_task_test.go
- test/v1alpha1/init_test.go
- test/v1alpha1/kaniko_task_test.go
> Try to fix skip tests

- openshift/e2e-tests-openshift.sh
- openshift/patches/0001-Skip-duplications-tests.patch
- openshift/patches/README.md
- openshift/release/update-to-head.sh
And add a patch to  skip the duplicated e2e tests
> Update update-to-head to allow applying patch

- openshift/release/tektoncd-pipeline-v0.11.0-rc3.yaml
Add release.yaml v0.11.0-rc3 to release-v0.11.0-rc3 branch
> Releasing release.yaml v0.11.0-rc3

- openshift/release/update-to-head.sh
The patch format are *.patch
Thanks @nikhilthomas for pointing this.
> Fix applying patch

- openshift/release/tektoncd-pipeline-v0.11.1.yaml
> Releasing release.yaml v0.11.1

- openshift/resolve-yamls.sh
This will fix the image replacement as the
busybox and tianon/true image has sha also now
> Fix image replacement

- openshift/resolve-yamls.sh
Changes done as the busybox image has been removed and
changed to gcr.io/distroless/base:debug
> Fix generate yaml script to handle new image

- openshift/ci-operator/build-image/Dockerfile
- openshift/ci-operator/uidwrapper
Requires this changes to cherry-pick to fix CI
> Cherypick to 0.12.1 from master

- openshift/ci-operator/Dockerfile-git.in
- openshift/ci-operator/tekton-images/creds-init/Dockerfile
- openshift/ci-operator/tekton-images/git-init/Dockerfile
This will fix the dockerfile getting generated
as it is using wrong base image
> Fix dockerfile getting generated

- openshift/resolve-yamls.sh
Tested and verified by [PR](https://github.com/openshift/tektoncd-pipeline/pull/429) on release-next branch
The changes were introduced by [PR](https://github.com/tektoncd/pipeline/pull/2781)
> Update resolve yamls to fix image replace issue

- openshift/release/update-to-head.sh
I have some setup that not using openshift remote directly for pushing, so let's
allow redefining it...
> Allow redefining OPENSHIFT_REMOTE

- OWNERS_ALIASES
> remove hrishin from owners

- Makefile
- openshift/ci-operator/tekton-images/nop/Dockerfile
> Fix ci at least

- openshift/patches/0001-Remove-task-retry-since-too-flaky.patch
- openshift/patches/0002-Skip-duplicated-task-they-consume-too-much-memory-on.patch
- openshift/release/update-to-head.sh
And it's an anyway better patch format...
> We need to use git am since we don't have patch in the image

- openshift/patches/0001-Remove-task-retry-since-too-flaky.patch
- openshift/patches/0002-Skip-duplicated-task-they-consume-too-much-memory-on.patch
who knows maybe one day ill get it right. I missed a double quote.
I blame me trying to use vscode and being buggy as ** for me when doing
go devlopment.
Same goes for emacs or vim to be honest,
So well that's my excuses 😜
> Fix patches again

- openshift/release/release-notes.md
- openshift/release/tektoncd-pipeline-v0.17.1.yaml
Add release.yaml v0.17.1
Add release note
> Releasing release.yaml v0.17.1

- openshift/ci-operator/tekton-images/controller/Dockerfile
- openshift/ci-operator/tekton-images/creds-init/Dockerfile
- openshift/ci-operator/tekton-images/entrypoint/Dockerfile
- openshift/ci-operator/tekton-images/gcs-fetcher/Dockerfile
- openshift/ci-operator/tekton-images/git-init/Dockerfile
- openshift/ci-operator/tekton-images/imagedigestexporter/Dockerfile
- openshift/ci-operator/tekton-images/kubeconfigwriter/Dockerfile
- openshift/ci-operator/tekton-images/pullrequest-init/Dockerfile
- openshift/ci-operator/tekton-images/webhook/Dockerfile
Signed-off-by: Vincent Demeester <vdemeest@redhat.com>
> Fix Dockerfile generation

- openshift/release/tektoncd-pipeline-v0.19.0.yaml
Signed-off-by: Vincent Demeester <vdemeest@redhat.com>
> Add release-v0.19 yaml

- openshift/release/generate-release.sh
this add another sed to change devel to $tag
if -version is used as args
cc: @piyush-garg
> change devel to $tag

- openshift/release/tektoncd-pipeline-v0.21.0.yaml
Signed-off-by: Pradeep Kumar <pradkuma@redhat.com>
> Releasing release.yaml v0.21.0

- openshift/release/update-to-head.sh
This replace the docker.io images with a mirror which doesn't get rate limited.
We prefer to use ecr since closest to our AWS openshift-install but sometime gcr.io may be better.
For example on busybox the ecr image (public.ecr.aws/runecast/busybox) doesn't
have latest tags while the gcr one does so using gcr here...
> Replace docker.io images with a mirror from public cloud provider

- openshift/release/update-to-head.sh
> Make sure to add -a to commit or files would not be staged

- openshift/release/update-to-head.sh
Set feature flag `disable-home-env-overwrite` to false
Set feature flag `disable-working-directory-overwrite` to false
Signed-off-by: Nikhil Thomas <nikthoma@redhat.com
> Modify update-to-head.sh to set feature flags

- openshift/release/update-to-head.sh
> Minor fix in update-to-head script

- openshift/release/update-to-head.sh
Add missing `""`s in update-to-head.sh
> Fix a typo

- openshift/release/tektoncd-pipeline-v0.24.3.yaml
Set `disable-home-env-overwrite: "false"`
Ser `disable-working-directory-overwrite: "false"`
Signed-off-by: Nikhil Thomas <nikthoma@redhatcom>
> Fix release.yaml for v0.24.3 release

- test/init_test.go
* upstream/midstream tests verifies for default service account when user creates a namespace, by default it's hard coded [here](https://github.com/tektoncd/pipeline/blob/main/test/init_test.go#L147) to `default` 
* so if we install pipelines components via operator it sets `default-service-account` to `pipeline` in `config-defaults` config map!
* so it's safe to use this patch both in upstream/downstream as it actually waits for right service account before it actually executest the tests  
As the author of this PR, please check off the items in this checklist:
functionality, content, code)
> Add check to defaultsa
